# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [18]:
import numpy as np

2. Create a null vector of size 10 

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [20]:
arr3 = np.arange(10,49)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [21]:
np.shape(arr3)

(39,)

5. Print the type of the previous array in question 3

In [22]:
type(arr3)

numpy.ndarray

6. Print the numpy version and the configuration


In [23]:
print(np.__version__)
print(np.__config__.show())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3/anaconda3/envs/piaic\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3/anaconda3/envs/piaic\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3/anaconda3/envs/piaic\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_librarie

7. Print the dimension of the array in question 3


In [24]:
np.ndim(arr3)

1

8. Create a boolean array with all the True values

In [25]:
arr3 != 5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

9. Create a two dimensional array




In [26]:
arr9 = np.arange(16).reshape(4,4)
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

10. Create a three dimensional array



In [27]:
arr10 = np.arange(48).reshape(3,4,4)
arr10

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [28]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [29]:
arr12 = np.zeros(10)
print(arr12)
print("===============================")
arr12[5] = 1
print(arr12)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## 13. Create a 3x3 identity matrix

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [31]:
# arr = np.array([1, 2, 3, 4, 5],dtype=np.float64)
arr14 = np.array([1, 2, 3, 4, 5])
arr14.astype('float64')

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [32]:
arr15a = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr15b = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr15a * arr15b

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [33]:
arr16a = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr16b = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr16a == arr16b

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [34]:
arr17 = np.arange(10)
arr17a = arr17[arr % 2 == 1]
arr17a

NameError: name 'arr' is not defined

18. Replace all odd numbers to -1 from previous array

In [35]:
arr17a[:] = -1
arr17a

NameError: name 'arr17a' is not defined

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [36]:
arr19 = np.arange(10)
arr19[5:9] = 12
arr19

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [37]:
arr20 = np.ones((5,5))
arr20[1:-1, 1:-1] = 0
arr20

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [38]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
arr4 = np.arange(10).reshape(2,5)
print(arr4)
arr4[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [41]:
arr24 = np.arange(10).reshape(2,5)
print(arr24)
arr24[1,1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [42]:
arr25 = np.arange(1,10).reshape((3,-1))
print(arr25)
arr25[:2,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
arr26 = np.arange(100).reshape(10,10)
print(arr26)
arr26a = arr26.min(),arr26.max()
print(arr26a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(0, 99)


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
(np.intersect1d(a,b))

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
# c = [x in a for x in b]
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != "Will"]

array([[-2.02639478, -1.26792962,  1.04028316, -1.41296891],
       [-0.40019825, -0.14746057,  0.01875597,  0.09341167],
       [-0.15127219, -0.14454613,  0.33140916,  1.19046703],
       [ 1.68673695,  0.46075555,  0.0152894 , -0.94841617],
       [ 1.80277797, -0.05504786, -1.40281532,  0.78168035]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

mask = (names == "Will") | (names == "Joe")
data[mask]

array([[ 1.79182437, -0.91172145,  0.62672977, -1.1397232 ],
       [ 0.31152047, -0.82318269, -0.35940011, -0.72348192],
       [ 0.2950056 ,  1.72439908,  0.87542428,  1.05788771],
       [ 1.76045997, -0.24238786, -0.00803279,  0.96410846],
       [-0.05274198, -0.19590182,  0.94716172, -0.91568532]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [52]:
arr31=np.arange(1,16,dtype="float64")
arr31.shape = (5,3)
arr31

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [53]:
arr32 = np.arange(1,17)
arr32.shape = (2,2,4)
arr32

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [54]:
arr32.swapaxes(2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [55]:
arr34 = np.arange(10)
arr34a = np.sqrt(arr34)
print(arr34a)
arr34a[arr34a < 0.5]


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [56]:
arr35a=np.random.randint(12, size = 12)
print(arr35a)
arr35b=np.random.randint(12, size = 12)
print(arr35b)
np.maximum(arr35a,arr35b)

[ 2  0  8  9  1  3 10 10  6 10  4  9]
[ 8  3  5 11  7  4  8  2  4  1  6 11]


array([ 8,  3,  8, 11,  7,  4, 10, 10,  6, 10,  6, 11])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [57]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names = np.unique(names)
print(names)
np.sort(names)
print(names)

['Bob' 'Joe' 'Will']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [58]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [69]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
x=np.delete(sampleArray,obj=2,axis=1)
print("deleting column \n",x)
newColumn = np.array([[10,10,10]])
y=np.insert(x,2,newColumn,1)
print("New column\n",y)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
deleting column 
 [[34 43]
 [82 22]
 [53 94]]
New column
 [[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [60]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [61]:
arr40=np.random.randint(5, size=20)
print(arr40)
np.cumsum(arr40)

[0 2 2 3 3 0 0 1 4 2 0 1 4 0 4 2 0 1 0 1]


array([ 0,  2,  4,  7, 10, 10, 10, 11, 15, 17, 17, 18, 22, 22, 26, 28, 28,
       29, 29, 30], dtype=int32)